- name: Hammerhead Debian ðŸ––
  hosts: localhost
  become: yes
  tasks:
    - name: Install btop âš™ï¸
      ansible.builtin.package:
        name: btop
        state: present

    - name: Install fastfetch ðŸª„
      ansible.builtin.package:
        name: fastfetch
        state: present

    - name: Install fzf ðŸ”Ž
      ansible.builtin.package:
        name: fzf
        state: present

    - name: Install tmux ðŸ’»
      ansible.builtin.shell: |
        apt install tmux -y

    - name: Catpuccin for tmux
      ansible.builtin.shell: |
        mkdir -p ~/.config/tmux/plugins/catppuccin
        git clone -b v2.1.0 https://github.com/catppuccin/tmux.git ~/.config/tmux/plugins/catppuccin/tmux
        echo "run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux" >> ~/.tmux.conf
      become: no

    # Thanks tmux - https://tmuxcheatsheet.com/theming-and-customizing/
    - name: Configuring tmux
      ansible.builtin.blockinfile:
        path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.tmux.conf"
        block: |
          # Options to make tmux more pleasant
          set -g mouse on
          set -g default-terminal "tmux-256color"

          # Configure the catppuccin plugin
          set -g @catppuccin_flavor "mocha" # latte, frappe, macchiato, or mocha
          set -g @catppuccin_window_status_style "rounded" # basic, rounded, slanted, custom, or none

          # Load catppuccin
          run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
          # For TPM, instead use `run ~/.config/tmux/plugins/tmux/catppuccin.tmux`

          # Make the status line pretty and add some modules
          set -g status-right-length 100
          set -g status-left-length 100
          set -g status-left ""
          set -g status-right "#{E:@catppuccin_status_application}"
          set -agF status-right "#{E:@catppuccin_status_cpu}"
          set -ag status-right "#{E:@catppuccin_status_session}"
          set -ag status-right "#{E:@catppuccin_status_uptime}"
          set -agF status-right "#{E:@catppuccin_status_battery}"

          run ~/.config/tmux/plugins/tmux-plugins/tmux-cpu
      become: no

    - name: Install nvm
      ansible.builtin.shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
      args:
        creates: "{{ lookup('ansible.builtin.env', 'HOME') }}/.nvm/nvm.sh"

    - name: Install npm using nvm
      ansible.builtin.shell: |
        export NVM_DIR="{{ lookup('ansible.builtin.env', 'HOME') }}/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install --lts
      args:
        creates: "{{ lookup('ansible.builtin.env', 'HOME') }}/.nvm/versions/node"

    # https://github.com/catppuccin/gnome-terminal
    - name: Install catpuccin in gnome terminal
      ansible.builtin.shell: |
        curl -L https://raw.githubusercontent.com/catppuccin/gnome-terminal/v1.0.0/install.py | python3 -
      # making sure we install this in the current profile and not for root
      become: no
